version: 0.2

env:
  shell: bash
  parameter-store:
    KEYRINGFILE: /drakkar/java-sdk/KEYRINGFILE
    OSSRH_USER: /drakkar/java-sdk/OSSRH_USER
    OSSRH_PASSWORD: /drakkar/java-sdk/OSSRH_PASSWORD
    SIGNING_KEY: /drakkar/java-sdk/SIGNING_KEY
    SIGNING_PASSPHRASE: /drakkar/java-sdk/SIGNING_PASSPHRASE
phases:
  pre_build:
    commands:
      - cp /home/gradle/project/* .
      # - mv gradle.properties.local gradle.properties
      - mv gradle.properties.ci gradle.properties
  build:
    commands:
      - gradle build
      - gradle publishAllPublicationsToMavenRepository